description: 'fly arena dataset   time_step: 4'
dataset: 'fly_1'
data_folder_name: '/groups/saalfeld/home/allierc/signaling/fly/flydata.npz'

simulation:
  params: [[1.6233, 1.0413, 1.6012, 1.5615], [1.7667, 1.8308, 1.0855, 1.9055],  [1.7226, 1.7850, 1.0584, 1.8579]]
  func_params: [['arbitrary', 0, 0], ['arbitrary', 1, 1], ['arbitrary', 2, 2]]
  min_radius: 0
  max_radius: 50
  n_particles: 10
  n_particle_types: 1
  n_frames: 58642
  sigma: 0.005
  delta_t: 1
  dpos_init: 0
  boundary: 'no'
  dimension: 3

graph_model:
  particle_model_name: 'PDE_A_fly'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 7
  output_size: 3
  hidden_dim: 128
  n_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.04, 0.03]

training:

  n_runs: 23
  device: 'auto'
  n_epochs: 20
  batch_size: 1

  time_step: 4

  small_init_batch_size: False
  sparsity: 'none'
  rotation_augmentation: True
  data_augmentation_loop: 1
  fix_cluster_embedding: True

  learning_rate_start: 0.00001
  learning_rate_embedding_start: 0.00001






