description: LLM-guided pattern exploration (parallel)
dataset: diffusiophoresis_Claude_03
simulation:
  params:
  - - -10
    - 10
    - 100
    - -100
    - 1.6
    - 1.0
    - 1.6
    - 1.5
  - - 8
    - -8
    - -60
    - 60
    - 1.8
    - 1.8
    - 1.1
    - 1.9
  - - -4
    - 4
    - 40
    - -40
    - 2.0
    - 1.0
    - 2.0
    - 1.0
  params_mesh:
  - - 0.05
    - 15.0
    - 5.5
    - 7.5
    - 0.04
    - -8
  - - 0.8
    - 8
    - 0.0
    - 0.0
    - 0.1
    - 0.0
  - - 1.0
    - 100
    - -100
    - 0.05
    - 0.0
    - 0.3
  min_radius: 0
  max_radius: 0.2
  n_particles: 9600
  n_particle_types: 3
  n_frames: 2000
  n_nodes: 22500
  n_node_types: 1
  sigma: 0.005
  delta_t: 0.0005
  dpos_init: 0
  boundary: 'no'
  node_value_map: input_data/pattern_Null.tif
  node_coeff_map: ''
  shuffle_particle_types: false
graph_model:
  field_type: diffusiophoresis
  particle_model_name: PDE_ParticleField_D
  mesh_model_name: Diffusiophoresis_Mesh
  prediction: first_derivative
  input_size: 5
  output_size: 2
  hidden_dim: 128
  n_layers: 5
  aggr_type: mean
  embedding_dim: 2
  update_type: none
plotting:
  colormap: tab10
  arrow_length: 2
  ylim:
  - -0.04
  - 0.03
training:
  n_runs: 1
  device: cuda:1
  n_epochs: 20
  batch_size: 8
  small_init_batch_size: false
  sparsity: replace_embedding_function
  cluster_method: distance_plot
  rotation_augmentation: true
  data_augmentation_loop: 100
  fix_cluster_embedding: true
claude:
  n_iter_block: 8
  ucb_c: 1.414
